### ISSUE TITLE
[bad name] IndexError: Replacement index 1 out of range for positional args tuple

### ISSUE THREAD

**Issue by unruhschuh** [pavelliavonau/cmakeconverter#128] opened 2021-05-03 09:11 UTC
Using cmake-converter I get the following error. Sorry, I cannot supply the .sln

```
$ cmake-converter -s something.sln
0.000128 processes count = 8
0.000190 warnings level = 2
0.321987 1> Conversion started: Project * 
0.322295 2> Conversion started: Project * 
0.324328 3> Conversion started: Project * 
0.325688 6> Conversion started: Project * 
0.326207 7> Conversion started: Project * 
0.326785 8> Conversion started: Project * 
0.330464 4> Conversion started: Project * 
0.335871 9> Conversion started: Project * 
0.399056 10> Conversion started: Project * 
0.404218 14> Conversion started: Project * 
0.425272 15> Conversion started: Project * 
0.433851 16> Conversion started: Project * 
0.446150 17> Conversion started: Project * 
0.489221 18> Conversion started: Project * 
0.512468 19> Conversion started: Project * 
0.517032 20> Conversion started: Project * 
0.527030 21> Conversion started: Project * 
0.574690 22> Conversion started: Project * 
0.575536 24> Conversion started: Project * 
0.630752 26> Conversion started: Project * 
0.664682 25> Conversion started: Project * 
0.702116 27> Conversion started: Project * 
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/data_converter.py", line 266, in run_conversion
    converted = self.convert_project(
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/data_converter.py", line 235, in convert_project
    self.collect_data(context)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/data_converter.py", line 53, in collect_data
    context.parser.parse(context)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 145, in parse
    self._parse_nodes(context, root)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/parser.py", line 92, in _parse_nodes
    self._parse_attributes(context, child_node)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/parser.py", line 119, in _parse_attributes
    attributes_handlers[attr](context, attr, node.get(attr), node)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 291, in __parse_condition
    cmake_setting = make_cmake_configuration(context, found.group(1))
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/utils.py", line 508, in make_cmake_configuration
    return "{}|{}".format(*sln_conf_arch)
IndexError: Replacement index 1 out of range for positional args tuple
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lez/.local/bin/cmake-converter", line 8, in <module>
    sys.exit(main())
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/main.py", line 144, in main
    converter.convert_solution(project_context, os.path.abspath(args.solution))
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/visual_studio/solution.py", line 331, in convert_solution
    results = self.do_conversion(project_context, input_data_for_converter)
  File "/home/lez/.local/lib/python3.8/site-packages/cmake_converter/data_converter.py", line 298, in do_conversion
    results = pool.map(self.run_conversion, input_converter_data_list)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: Replacement index 1 out of range for positional args tuple
```

**Comment by pavelliavonau** [comment] 2021-05-03 15:53
No info. So, investigate by yourself

**Comment by unruhschuh** [comment] 2021-05-03 16:29
Apparently one of the projects in my solution does not define the architecture for one of the Release configurations, and hence the   result of `sln_configuration.split('|')` in `make_cmake_configuration()` in `utils.py` results in only `Release`. I "fixed" it like so:

``` python
def make_cmake_configuration(context, sln_configuration):
      """ Tries to make cmake configuration name from sln_configuration """
      sln_conf_arch = sln_configuration.split('|')
      if len(sln_conf_arch) == 1:        # <---
          sln_conf_arch.append("Win32")  # <---
      genex_invalid_regex = r'[^A-Za-z0-9_]'
      sln_conf_arch[0] = escape_string(context, genex_invalid_regex, sln_conf_arch[0])
      return "{}|{}".format(*sln_conf_arch)
```

Could you tell me if either there is something wrong with my vcxproj file or should `make_cmake_configuration` assume some reasonable fallback architecture as done above?

Edit: I might add that the solution and the vcxproj files are generated by a make file and so it is quite possible, that this would not happen with a vcxproj file created by Visual Studio.

**Comment by pavelliavonau** [comment] 2021-05-03 17:37
It's inconsistency at your solution files. You should investigate and fix it by yourself. Your fix is incorrect and can't be applied as general.
Also: I'm not going to support to vs solutions generated with third party tools. It's written at doc's. Have you checked docs before? Also pay attention on warnings that converter give to you and check verbose output in single thread.

**Closed as completed** 2021-08-09 12:00 UTC

**Comment by autoantwort** [comment] 2021-09-10 10:39
I got the exact same error at our company project, but we don't use qt and afaik only use the vs gui to edit the projects.

**Comment by xakod** [comment] 2022-02-10 14:58
Looks like I have the same
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\data_converter.py", line 285, in run_conversion
    converted = self.convert_project(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\data_converter.py", line 252, in convert_project
    self.collect_data(context)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\data_converter.py", line 53, in collect_data
    context.parser.parse(context)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 145, in parse
    self._parse_nodes(context, root)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\parser.py", line 101, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 190, in __parse_property_group
    self._parse_nodes(context, node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\parser.py", line 92, in _parse_nodes
    self._parse_attributes(context, child_node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\parser.py", line 119, in _parse_attributes
    attributes_handlers[attr](context, attr, node.get(attr), node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 291, in __parse_condition
    cmake_setting = make_cmake_configuration(context, found.group(1))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\utils.py", line 508, in make_cmake_configuration
    return "{}|{}".format(*sln_conf_arch)
IndexError: Replacement index 1 out of range for positional args tuple
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\cmake-converter.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\main.py", line 144, in main
    converter.convert_solution(project_context, os.path.abspath(args.solution))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\visual_studio\solution.py", line 330, in convert_solution
    results = self.do_conversion(project_context, input_data_for_converter)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cmake_converter\data_converter.py", line 317, in do_conversion
    results = pool.map(self.run_conversion, input_converter_data_list)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
IndexError: Replacement index 1 out of range for positional args tuple
```
Is there any hint how to find sln with problem?

**Comment by habi498** [comment] 2022-05-22 17:56
I also got that error
I think it is an error with the parser.py in 
make_cmake_configuration, there is a split command using ('|')
But some project does not have '|' in condition. See for instance the one i was working with https://github.com/Lexikos/AutoHotkey_L.
I spend 3 hours trying to fixing this.

**Comment by pavelliavonau** [comment] 2022-05-22 20:27
@habi148, What condition string do you mean?

**Comment by habi498** [comment] 2022-05-23 10:49
Sir,  
I have this line in my visual studio vcxproj line 88,  which is giving me error. (the error the same as topic)
![IMG_20220523_161213](https://user-images.githubusercontent.com/61708020/169802506-963705c2-db4f-4950-a410-bf97e1864cee.jpg)
As i mentioned before,  parser.py try to split the condition string based on the 'pipe' character. And the condition string unfortunately does not have the pipe character.
The condition string is like platform ==Win32 OR platform ==x64. It cannot be typed here.
https://github.com/Lexikos/AutoHotkey_L/blob/6dbfc34f75c8236bed44eb6bfabce8e37801a6bd/AutoHotkeyx.vcxproj#L88

**Comment by pavelliavonau** [comment] 2022-05-23 20:51
How can it be created with visual studio UI? What are steps to reproduce?

**Comment by habi498** [comment] 2022-05-24 08:18
No, that project was not created by me. So i do not know how it is made. I am trying to convert it to cmake project so that it can be used elsewhere.

**Comment by pavelliavonau** [comment] 2022-05-24 08:43
Cmake converter does not and won't support handmade msbuild files. It's not parser of msbuild language. Sorry.
You may exclude handmade file from solution, convert and and try to translate unsupported file by yourself.

**Comment by habi498** [comment] 2022-10-11 08:11
I understand.

**Comment by iddm** [comment] 2022-12-27 13:54
I have the same issue. I don't know how the file was generated but I can give a link to it (also github), nevertheless...

> Cmake converter does not and won't support handmade msbuild files. It's not parser of msbuild language. Sorry. You may exclude handmade file from solution, convert and and try to translate unsupported file by yourself.

Then you should state it clearly in the readme file because your readme file is confusing lots of people by not having this mentioned right in the beginning. You don't see this, do you? It says **"This project aims to facilitate the conversion of Visual Studio solution to CMake projects. The goal is to give to a Python script, a *.sln file, and output a set of CMakeLists.txt that may be used for generating visual studio solution backward as perfect as possible. Project is useful for porting VS projects into CMake build system."**.

People aren't frustrated at you, they are frustrated cuz they thought it would work, just as it is said in the readme file. False advertisements lead to false expectations.

Either way, what I would expect from this github issue in particular is at least giving a hint of what is expected to work and what not, so I could take a look at what might be changed within the sln file myself. Everyone here is left with no idea what is expected to be parsed and what is not. To the proposed solutions you just say "It is incorrect" like you know what would be correct but you'd never do it, for people don't deserve it. Or, perhaps, even nobody deserves to know how to actually run the tool and to have it actually do something, rather than throwing errors.

**Comment by strimpa** [comment] 2024-04-09 09:54
I had the same issue. For me the issue was a Qt lib in the mix.
The issue is indeed the build config string in the vcproj file. Visual Studio typically concatanates with the pipe char like "Release|x64".

The workaround for me was to simply add a a pipe char **to both sides** of the string comparison in the condition statement in the "Globals" PropertyGroup:
`<QtMsBuild Condition="'$(QtMsBuild)'=='' OR !Exists('$(QtMsBuild)\qt.targets')">$(MSBuildProjectDirectory)\QtMsBuild</QtMsBuild>`
to
`<QtMsBuild Condition="'$(QtMsBuild)|'=='' OR !Exists('$(QtMsBuild)\qt.targets|')">$(MSBuildProjectDirectory)\QtMsBuild</QtMsBuild>`

So my entire PropertyGroups looks like 
`  <PropertyGroup Label="Globals">
    <ProjectGuid>{6DABEED8-D6E1-4167-B4CB-87B711166414}</ProjectGuid>
    <Keyword>QtVS_v304</Keyword>
    <WindowsTargetPlatformVersion Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">10.0.22621.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformVersion Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">10.0.22621.0</WindowsTargetPlatformVersion>
    <QtMsBuild Condition="'$(QtMsBuild)|'=='' OR !Exists('$(QtMsBuild)\qt.targets|')">$(MSBuildProjectDirectory)\QtMsBuild</QtMsBuild>
  </PropertyGroup>
`

Hope this helps someone.

**Comment by strimpa** [comment] 2024-04-09 10:10
Optionally, the code looks like it's expecting a solution configuration and stores that as the "current" one, so it seems reasonable to assume other condition statements can be ignored.
E.g. in \cmake_converter\visual_studio\vcxproj\parser.py, def __parse_condition() change
`        if not found:
            return
`
to 
`        if not found or "|" not in found.group(1):
            return
`

**Comment by pturley0** [comment] 2025-12-09 01:14
In case it helps anyone else, here's how I fixed this problem for myself.

```
    def __parse_condition(self, context, attr_name, condition_value, node):
        del attr_name

        # This code wants to pick out configuration information, which it knows appears in a
        # conditional test like this:
        #
        #  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
        #
        # So, this code tests for anything that's being compared with a double-equals sign to
        # anything else in single quotes.
        #
        # Unfortunately (and kind of obviously), configuration information isn't the *only* thing
        # that is tested like this, for example:
        #
        #    <_VCToolsVersionProps Condition="'$(VisualStudioVersion)'=='17.0'">$(VsInstallRoot)\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props</_VCToolsVersionProps>
        #
        # So, this code matches stuff it's not supposed to, and that can cause a crash.
        #
        # Here, we make the match string much more specific, so this code only picks out what it's
        # supposed to.
        #
        #found = re.search(r".*=='(.*)'", condition_value)
        found  = re.search(r".*=='(.*\|.*)'", condition_value)
        if not found:
            return

        cmake_setting = make_cmake_configuration(context, found.group(1))
        setting = tuple(cmake_setting.split('|'))
        if setting in context.settings:
            context.current_setting = setting
            context.flags.prepare_context_for_flags(context)
            self.reset_current_setting_after_parsing_node(node)
        else:
            context.current_setting = (None, None)
            raise StopParseException()
```
