### ISSUE TITLE
Error converting my VS2022 project using Converter 2.20

### ISSUE THREAD

**Issue by perdrix52** [pavelliavonau/cmakeconverter#155] opened 2024-10-20 11:31 UTC
As requested I have run with the w4 -v -j1 options to meet your reporting requirements.    The Env-var QtMsBuild is set to:
QtMsBuild=C:\Users\amonra\AppData\Local\QtMsBuild

 Expected output is converted projects, instead I get:

C:\Users\amonra\Documents\GitHub\DSS>cmake-converter -w4 -v -j1 -s DeepSkyStacker.VS2022.sln
0.000000 Converter runs in verbose mode
0.000000 processes count = 1
0.000000 warnings level = 4
0.001000 INFO : ------- Started parsing solution C:\Users\amonra\Documents\GitHub\DSS\DeepSkyStacker.VS2022.sln -------
0.007979 INFO : Version of solution is 12.00
0.007979 INFO : Start parsing projects info (Project .. EndProject)
0.007979 INFO :     Found project "DeepSkyStackerCL\DeepSkyStackerCL.vcxproj" with {CB7B75F1-08F4-4C8D-A7EF-29CDCE9A67F1}
0.008979 INFO :     Found project "DeepSkyStackerLive\DeepSkyStackerLive.vcxproj" with {6290D6C2-900F-496C-A522-D5C8BF807066}
0.008979 INFO :     Found project "DeepSkyStacker\DeepSkyStacker.vcxproj" with {90721C24-BC43-450A-ADED-3417280D075B}
0.008979 INFO :     Found project "LibTiff\libtiff.vcxproj" with {D5FB2402-A821-4474-91E7-07F0DD5866F0}
0.008979 INFO :     Found project "ZCLass\ZCLass.vcxproj" with {1747F255-9CB9-472B-8FEE-9E0BBFBAD49D}
0.009973 INFO :     Found project "LibRaw\buildfiles\libraw.vcxproj" with {A71D2131-F425-381F-8A9A-29D60132A046}
0.009973 INFO :     Found project "DeepSkyStackerTest\DeepSkyStackerTest.vcxproj" with {487E5070-BF81-4DEF-BE9F-510EEACE627B}
0.009973 INFO :     Found project "DeepSkyStackerKernel\DeepSkyStackerKernel.vcxproj" with {CB7B75F1-08F4-4C8D-A7EF-2AA33E9A67F1}
0.009973 INFO : Start parsing GlobalSection(SolutionConfigurationPlatforms) = preSolution
0.009973 INFO :     Found sln setting "Debug|x64"
0.009973 INFO :     Found sln setting "Release|x64"
0.009973 INFO : Start parsing GlobalSection(ProjectConfigurationPlatforms) = postSolution (Mapping sln-setting -> project-setting)
0.010971 INFO :     "Debug|x64" -> "Debug|x64" for DeepSkyStackerCL
0.010971 INFO :     "Release|x64" -> "Release|x64" for DeepSkyStackerCL
0.010971 INFO :     "Debug|x64" -> "Debug|x64" for DeepSkyStackerLive
0.010971 INFO :     "Release|x64" -> "Release|x64" for DeepSkyStackerLive
0.010971 INFO :     "Debug|x64" -> "Debug|x64" for DeepSkyStacker
0.010971 INFO :     "Release|x64" -> "Release|x64" for DeepSkyStacker
0.011970 INFO :     "Debug|x64" -> "Debug|x64" for libtiff
0.011970 INFO :     "Release|x64" -> "Release|x64" for libtiff
0.011970 INFO :     "Debug|x64" -> "Debug|x64" for ZCLass
0.011970 INFO :     "Release|x64" -> "Release|x64" for ZCLass
0.011970 INFO :     "Debug|x64" -> "Debug|x64" for libraw
0.011970 INFO :     "Release|x64" -> "Release|x64" for libraw
0.011970 INFO :     "Debug|x64" -> "Debug|x64" for DeepSkyStackerTest
0.011970 INFO :     "Release|x64" -> "Release|x64" for DeepSkyStackerTest
0.011970 INFO :     "Debug|x64" -> "Debug|x64" for DeepSkyStackerKernel
0.011970 INFO :     "Release|x64" -> "Release|x64" for DeepSkyStackerKernel
0.011970 INFO : ------ Finished parsing solution C:\Users\amonra\Documents\GitHub\DSS\DeepSkyStacker.VS2022.sln -------
0.012966 1> INFO : ------ Starting 1 -------
0.012966 1> INFO : Initialization data for conversion of project C:\Users\amonra\Documents\GitHub\DSS\DeepSkyStacker.VS2022.sln
0.013963 1> INFO : == start making default flags ==
0.013963 1> INFO : == end making default flags ==
0.013963 1> Conversion started: Project DeepSkyStackerCL
0.013963 1> INFO : Collecting data for project C:\Users\amonra\Documents\GitHub\DSS\DeepSkyStackerCL\DeepSkyStackerCL.vcxproj
0.029965 1> INFO : Parsing... line 3 node ItemGroup attrib {'Label': 'ProjectConfigurations'}
0.029965 1> INFO : Parsing... line 4 node ProjectConfiguration attrib {'Include': 'Debug|x64'}
0.029965 1> INFO : Parsing... line 8 node ProjectConfiguration attrib {'Include': 'Release|x64'}
0.030944 1> INFO : Parsing... line 13 node PropertyGroup attrib {'Label': 'Globals'}
0.030944 1> INFO : Parsing... line 14 node ProjectGuid attrib {}
0.030944 1> INFO : Parsing... line 15 node RootNamespace attrib {}
0.030944 1> INFO : Parsing... line 16 node Keyword attrib {}
0.031951 1> INFO : Parsing... line 17 node Keyword attrib {}
0.031951 1> INFO : Parsing... line 18 node QtMsBuild attrib {'Condition': "'$(QtMsBuild)'=='' OR !Exists('$(QtMsBuild)\\qt.targets')"}
0.031951 1> WARN L3 : file:/C:/Users/amonra/Documents/GitHub/DSS/DeepSkyStackerCL/DeepSkyStackerCL.vcxproj(18): string from solution fixed for CMake "
' OR !Exists('$(QtMsBuild)\qt.targets" -> "ORExistsQtMsBuildqttargets"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\cmake-converter.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\main.py", line 144, in main
    converter.convert_solution(project_context, os.path.abspath(args.solution))
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\visual_studio\solution.py", line 330, in convert_solution
    results = self.do_conversion(project_context, input_data_for_converter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\data_converter.py", line 320, in do_conversion
    results.append(self.run_conversion(data_for_converter))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\data_converter.py", line 285, in run_conversion
    converted = self.convert_project(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\data_converter.py", line 252, in convert_project
    self.collect_data(context)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\data_converter.py", line 53, in collect_data
    context.parser.parse(context)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 145, in parse
    self._parse_nodes(context, root)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\parser.py", line 101, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 190, in __parse_property_group
    self._parse_nodes(context, node)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\parser.py", line 92, in _parse_nodes
    self._parse_attributes(context, child_node)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\parser.py", line 119, in _parse_attributes
    attributes_handlers[attr](context, attr, node.get(attr), node)
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\visual_studio\vcxproj\parser.py", line 291, in __parse_condition
    cmake_setting = make_cmake_configuration(context, found.group(1))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cmake_converter\utils.py", line 508, in make_cmake_configuration
    return "{}|{}".format(*sln_conf_arch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Replacement index 1 out of range for positional args tuple

C:\Users\amonra\Documents\GitHub\DSS>

Thanks
David

**Comment by perdrix52** [comment] 2024-10-20 11:46
[DeepSkyStacker.VS2022.zip](https://github.com/user-attachments/files/17450078/DeepSkyStacker.VS2022.zip)

**Comment by pavelliavonau** [comment] 2024-10-21 21:23
This is a duplicate of #121.
You have not checked existing issues. Better, but not good yet.

**Closed as completed** 2024-10-21 21:24 UTC
Labels: duplicate
